config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

   namespace :admin do
    resources :users
    get '/users/become/:id', to: 'users#become'
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  belongs_to :user
  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }
  validates :description, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_future
  mount_uploader :image, ImageUploader

  def review_average
    reviews.average(:rating_out_of_ten) if reviews
  end


  class << self 

    def search(search_term)
      where("title LIKE ? OR director LIKE ?", "%#{search_term}%", "%#{search_term}%")
    end

  end

  protected

  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should probably be in the future") if release_date < Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 0 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => [:create]
  validates_presence_of :password_confirmation, :on => [:create]
  has_many :reviews, dependent: :destroy
  has_many :movies


  def full_name
    "#{firstname} #{lastname}"
  end


  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :admin?




  def admin?
    return if session[:admin_user_id]
    unless current_user && current_user.admin
      redirect_to movies_path
    end
  end




  def index
    if session[:admin_user_id]
      session[:user_id] = session[:admin_user_id]
      session[:admin_user_id] = nil
    end
    @admin = User.find(session[:user_id])
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

   def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    @user.save
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(post_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def create
  end

  def destroy
    @user = User.find(params[:id])
    flash.now[:alert] = "Successfully Deleted #{@user.full_name}"
    
    UserMailer.delete_notification(@user)

    @user.destroy
    redirect_to admin_users_path

  end


  def become
    session[:admin_user_id] = current_user.id
    session[:user_id] = params[:id]
    @temp_user_name = User.find(params[:id]).full_name
    redirect_to root_url
    flash[:alert] = "Temporarily logged in as #{@temp_user_name}"
  end



  protected

  def post_params
    params.require(:user).permit(:email, :firstname, :lastname, :admin)
  end


end


 # @books = Book.all.order(:title)   # an empty array of AR objects
 #    @books = @books.by_title(title) if title.present?
 #    @books = @books.on_sale         if on_sale
 #    @books = @books.in_price_range(0, max_price) if max_price.present? # should probably make this a scope / class method as well

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected


  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_sessions_path
    end
  end


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end


  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all.order(:title)
    @movies = @movies.search(params[:search]) if params[:search].present?
  end


  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end


  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end


  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end


  protected


  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :description, :image, :remote_image_url)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

  def current_user
    session[:user_id]
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @back = request.referrer
  end




  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin: Edit User</h1>
<%= form_for ([:admin, @user]) do |f| %>
   <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "email" %><br>
    <%= f.text_field "email", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box :admin %>
    <%= f.label "Admin Privileges" %><br>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>

<h1>Welcome <%= @admin.firstname.capitalize %></h1>
<%= link_to "create new user >", new_admin_user_path %>
<div class="spacer">
</div>

<div class="container">



  <% @users.each do |user| %>

    <h3><%= user.full_name %> | <%= user.email %>
    <% if user.admin? %>
      | Administrator
    <% else %>
     | Regular User
    <% end %>
     | <%= link_to "see user details", admin_user_path(user) %>
    </h3>
    <div class="separator">
    </div>
  <% end %>

  <%= paginate @users %>


</div> <!-- End container>

app/views/admin/users/new.html.erb
<h1>Admin: Create a New User</h1>
<%= form_for ([:admin, @user]) do |f| %>
   <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div>
<%= f.label "email" %><br>
 <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.check_box :admin %>
    <%= f.label "admin", "Admin Privileges" %><br>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/show.html.erb
<h1>Details for <%= @user.full_name %></h1>
<div class="admin-user-options">
  <p><em><%= link_to "edit user", edit_admin_user_path %></em></p>
  <p><em><%= link_to "delete user", admin_user_path(@user), :method => :delete, :"data-confirm" => "You sure?" %></em></p>
  <p><em><%= link_to "become this user", "/admin/users/become/#{@user.id}/" %></em></p>
</div>
<div class="spacer">
  <ul>
  <li><%= @user.email %></li>
  <li>Number of Movie Submissions: <%= @user.movies.count %></li>
  <li>Number of Reviews: <%= @user.reviews.count %></li>
  <li>Average Review: <%= @user.reviews.average(:rating_out_of_ten) %></li>
  </ul>

</div>

<div>
  <% if @user.reviews.any? %>
    <h4><%= @user.full_name %>'s Reviews:</h4>
      <% @user.reviews.each do |review| %>
      <p><em><%= link_to review.movie.title, movie_path(review.movie) %></em></p>
      <p><%= review.rating_out_of_ten %>/10. <%= review.text %></p>
      <div class="separator spacer"></div>
      <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>


    
  </small>
</footer>
 

app/views/layouts/_header.html.erb
<header>

  <% if session[:admin_user_id] %>
    <div class="ghost" style="border:1px solid black;">
      <p><b>This is a ghost session.</b> Click <%= link_to 'here', admin_users_path %> to log back in as admin.
      </p>
    </div>
  <% end %>

  <div class="login">
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>

    <% if current_user && current_user.admin? %>
        <%= link_to "Admin Settings", admin_users_path %>
    <% end %>
  </div>

  <div class="hero navbar-form">
    <%= render 'layouts/search_form' %>
  </div>

  <div class="clearfix spacer">
  </div>

  <hr>

</header>
 

app/views/layouts/_search_form.html.erb
<div class="search-form">

  <%= link_to image_tag("logo.png", :id => "logo"), "/" %>

    <div class="search pull-right form-group">
      <%= form_tag("/movies", method: "get") do %>
        <%= submit_tag("Search", :class => "btn btn-default") %>
        <%= text_field_tag(:search) %>
      <% end %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:multipart => true} do |f| %>
 <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "title" %><br>
    <%= f.text_field "title", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "director" %><br>
    <%= f.text_field "director", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.number_field "runtime_in_minutes", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "upload_image" %><br>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :remote_image_url, "or image URL" %><br>
    <%= f.text_field :remote_image_url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "description" %><br>
    <%= f.text_area "description", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-success" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="col-sm-4 col-md-4">
  <div class ="thumbnail">
    <%= link_to image_tag(movie.image_url), movie_path(movie), :class => "img-responsive" %>
  </div>
</div>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
  <div class="text-center spacer submit">
    <%= link_to "Submit a new movie >>", new_movie_path %> 
  </div>

  <% if @movies && @movies.count > 0 %>
  
  <div class="thumbnails">
    <%= render @movies %>
    
  </div>

  <% else %>
    <p>No results</p>
  <% end %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<div class="container">
  <div class="row spacer">
    <%= link_to "< Back to all movies", movies_path %><br/>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <%= image_tag(@movie.image_url, :class => "img-responsive") %>
    </div>
    <div class="col-sm-6">
      <h2><%= @movie.title %> <% if @movie.reviews.any? %> <%= @movie.review_average.round %>/10 <% end %> </h2>
      <p><em>release date: <%= formatted_date(@movie.release_date) %></em></p>
      <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
      <p><%= @movie.description %></p>

    <hr>
    <h3>Reviews of <em><%= @movie.title %></em></h3>
    <% if current_user %>
      <% @movie.reviews.each do |review| %>
        <p><%= review.text %></p>
        <p><%= review.rating_out_of_ten %>/10</p>
        <small><%= link_to review.user.full_name, user_path(review.user.id) %></small><br/>
        <div class="spacer separator"> 
        </div>
      <% end %>
      <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
    <% else %>
      <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
    <% end %>
    </div>
  </div>

</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "text" %><br>
    <%= f.text_area "text", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten", :class => "form-control rating" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
   <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "email" %><br>
    <%= f.text_field "email", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "password" %><br>
    <%= f.password_field "password", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= link_to "< Back", @back, :class => "row" %>

<div class="row">
  <h1><%= @user.full_name %></h1>
  <p><%= @user.full_name %> has submitted <%= @user.movies.count %> movies and
  <%= @user.reviews.count %> reviews. <%= @user.firstname %>'s average rating for movies is
  <%= @user.reviews.average(:rating_out_of_ten) %></p>
</div>


<div class="row">
  <% if @user.reviews.any? %>
    <h4><%= @user.firstname %>'s Reviews:</h4>
      <% @user.reviews.each do |review| %>
      <p><em><%= link_to review.movie.title, movie_path(review.movie) %></em></p>
      <p><%= review.rating_out_of_ten %>/10. <%= review.text %></p>
      <% end %>
  <% end %>
</div>